version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5400:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust 
  reviews-api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/reviews-api
      - /usr/src/reviews-api/node_modules
    ports:
      - 3030:3030
    environment:
      API_PORT: 3030
      DATABASE_URL: postgres://postgres:@postgres:5432/reviews
  reviews-service:
    build: ./service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/service
      - /usr/src/service/node_modules
    ports:
      - 4030:4030
    environment:
      SERVICE_PORT: 4030
      DATABASE_URL: postgres://postgres:@postgres:5432/reviews
  supersecretgoogleapi:
    build: ./supersecretgoogleapi
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./supersecretgoogleapi:/usr/src/supersecretgoogleapi
      - /usr/src/supersecretgoogleapi/node_modules
    ports:
      - 5030:5030
    environment:
      GOOGLE_API_PORT: 5030
      DATABASE_URL: postgres://googleapiuser:@postgres:5432/supersecretgoogleapidb
  web-app:
    image: "node:14-alpine"
    user: "node"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: "yarn run build"
    depends_on:
      - reviews-api
volumes:
  db_data:
